-- AI Native Development Dashboard - Database Initialization Script
-- Generated by Spec as Code Generator

CREATE DATABASE IF NOT EXISTS `ai_native_development_dashboard` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `ai_native_development_dashboard`;

SET FOREIGN_KEY_CHECKS = 0;

-- Table structure for table `ai_models` (undefined)
DROP TABLE IF EXISTS `ai_models`;
CREATE TABLE `ai_models` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NULL COMMENT '模型名称',
  `model_id` VARCHAR(255) NULL COMMENT '模型唯一标识符',
  `provider` VARCHAR(255) NULL COMMENT '模型提供商',
  `version` VARCHAR(255) NULL COMMENT '模型版本号',
  `description` VARCHAR(255) NULL COMMENT '模型描述',
  `capabilities` JSON NULL,
  `status` VARCHAR(255) NULL DEFAULT 'active',
  `test_sync_field` VARCHAR(255) NULL COMMENT '用于测试自动同步的字段',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `projects` (undefined)
DROP TABLE IF EXISTS `projects`;
CREATE TABLE `projects` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NULL COMMENT '项目名称',
  `description` VARCHAR(255) NULL COMMENT '项目描述',
  `status` VARCHAR(255) NULL DEFAULT 'planning',
  `priority` VARCHAR(255) NULL DEFAULT 'medium',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `usage_logs` (undefined)
DROP TABLE IF EXISTS `usage_logs`;
CREATE TABLE `usage_logs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `project_id` VARCHAR(255) NULL COMMENT '项目ID',
  `ai_model_id` VARCHAR(255) NULL COMMENT 'AI模型ID',
  `request_type` VARCHAR(255) NULL COMMENT '请求类型',
  `input_tokens` INT NULL,
  `output_tokens` INT NULL,
  `response_time` DECIMAL(10, 2) NULL,
  `cost` DECIMAL(10, 2) NULL,
  `success` TINYINT(1) NULL DEFAULT 1,
  `timestamp` DATETIME NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
